[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version =  '0.8.13'
evm_version = "paris"
gas_limit = 9223372036854775807
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_ARBITRUM}"